### ISSUE TITLE
issue124 branch

### ISSUE THREAD

**Issue by cal101** [ftomassetti/javaparser#4]
Hi again.

(feel free to stop me if this is not helpful (enough/yet))

I copied my small additions to the conrete syntax class of issue124 and gave it a try.
Parsing went through all my files without problems.
Then I switched to

`
            final Pair<ParseResult<CompilationUnit>, LexicalPreservingPrinter> p = LexicalPreservingPrinter.setup(
                    ParseStart.COMPILATION_UNIT, Providers.provider(content));
            final String printed = p.b.print(p.a.getResult().get());
`

Some parsing is REALLY slow now (multiple minutes)

Here a stack trace
`
   java.lang.Thread.State: RUNNABLE
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.inPhantomNode(PhantomNodeLogic.java:39)
        at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:32)
        at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$2.process(LexicalPreservingPrinter.java:222)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:40)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.ast.visitor.TreeVisitor.visitLeavesFirst(TreeVisitor.java:38)
        at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.storeInitialText(LexicalPreservingPrinter.java:226)
        at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.<init>(LexicalPreservingPrinter.java:121)
        at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.setup(LexicalPreservingPrinter.java:102)
`

**Comment by cal101** [comment]
His intentions were good :-)

"We limit how many levels up we check just for performance reasons."

I hacked "Node" to store the phantom information to get acceptable speed.

**Comment by cal101** [comment]
Some generation bug:
`
        private final Stack<Iterator<Triple>> its = new Stack<Iterator<Triple>>();
`

is changed to 
`
        private final Stack<Iterator<Triple>>> its = new Stack<Iterator<Triple>>>();
`

**Comment by cal101** [comment]
Test case:

```
    @Test
    public void printAGenericReference() {
        String code = "class A {private final Stack<Iterator<Triple>> its = new Stack<Iterator<Triple>>();}";
        considerCode(code);

        assertEquals("class A {private final Stack<Iterator<Triple>> its = new Stack<Iterator<Triple>>();}", lpp.print(cu));
    }
```

Hacky fix in TokenTextElement:
```
   TokenTextElement(int tokenKind, String text) {
        this.tokenKind = tokenKind;
        this.text = tokenKind == ASTParserConstants.GT ? ">" : text;
    }
```

**Comment by cal101** [comment]
Test case:
```

    @Test
    public void printAMultiCatch() {
        String code = "class A {{try { doit(); } catch (Exception | AssertionError e) {}}}";
        considerCode(code);

        assertEquals("class A {{try { doit(); } catch (Exception | AssertionError e) {}}}", lpp.print(cu));
    }
```

**Comment by cal101** [comment]
Other than that the only difference I saw was replacement of unicode escapes ("\uxxxx") 
with unicode characters. (mostly right, some wrong like \u0000 and maybe \ufffd)

Well done.

**Comment by ftomassetti** [comment]
yes, the unicode escape issue is known, we do not have a solution for that at the moment because it would require some quite significant refactoring of the underlying JavaCC parser.

Can you share your hack about the phantom nodes?

**Comment by cal101** [comment]
Do not try this at home. ;-)

```
/*
 * Copyright (C) 2007-2010 Júlio Vilmar Gesser.
 * Copyright (C) 2011, 2013-2016 The JavaParser Team.
 *
 * This file is part of JavaParser.
 *
 * JavaParser can be used either under the terms of
 * a) the GNU Lesser General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * b) the terms of the Apache License
 *
 * You should have received a copy of both licenses in LICENCE.LGPL and
 * LICENCE.APACHE. Please refer to those files for details.
 *
 * JavaParser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 */

package com.github.javaparser.printer.lexicalpreservation;

import com.github.javaparser.ast.Node;

/**
 * We want to recognize do not consider "phantom" nodes, like the fake type of variable in FieldDeclaration
 */
public class PhantomNodeLogic {

    public static boolean isPhantomNode(Node node) {
        boolean res;
        if (node.getHasPhantomNode()) {
            res = node.getPhantomNode();
        } else {
            res = (node.getParentNode().isPresent() && !node.getParentNode().get().getRange().get().contains(
            node.getRange().get()) || inPhantomNode(node, 3));
            node.setPhantomNode(res);
            node.setHasPhantomNode(true);
        }
        return res;
    }

    /**
     * A node contained in a phantom node is also a phantom node. We limit how many levels up we check just for performance reasons.
     */
    private static boolean inPhantomNode(Node node, int levels) {
        return /*levels >= 0
                && */(node.getParentNode().isPresent() && (isPhantomNode(node.getParentNode().get()) || inPhantomNode(node.getParentNode().get(), levels - 1)));
    }
}
```

**Comment by cal101** [comment]
PhantomNodeLogic does not use the level.

**Comment by cal101** [comment]
PhantomNodeLogic can fail for UnknownType, because they don't have a Range.

**Comment by cal101** [comment]
Maybe same problem again later:

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$storeInitialText$0(LexicalPreservingPrinter.java:229)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1249)

**Comment by cal101** [comment]
Will open new tickets for single issues when needed.
